import type { Metadata } from "next"
import "./globals.css"
import { Navbar } from "./components/navbar"

export const metadata: Metadata = {
	title: "rpxd",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
				></link>
			</head>
			<body className="container">
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	)
}
